name: vrptw-venv
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=21.1.5=hf598326_0
  - libffi=3.5.2=he5f378a_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_3
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.4=h4a912ad_0
  - ncurses=6.5=h5e97a16_3
  - numpy=2.3.4=py311h8685306_0
  - openssl=3.5.4=h5503f6c_0
  - pandas=2.3.3=py311hdb8e4fa_1
  - pip=25.2=pyh8b19718_0
  - python=3.11.0=h3ba56d0_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h1d1bf99_2
  - ruff=0.14.3=h382de68_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=h892fb3f_2
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - pip:
      - cplex==22.1.2.0
      - docplex==2.30.251
prefix: /Users/cuphead/miniforge3/envs/vrptw-venv
